services:
  - type: web
    name: api-smoothie
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: CORS_ORIGIN
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: JWT_ACCESS_PRIVATE_KEY
        sync: false
      - key: JWT_ACCESS_PUBLIC_KEY
        sync: false
      - key: JWT_REFRESH_PRIVATE_KEY
        sync: false
      - key: JWT_REFRESH_PUBLIC_KEY
        sync: false
      - key: JWT_ACCESS_EXPIRES_IN
        sync: false
      - key: JWT_REFRESH_EXPIRES_IN
        sync: false
